# .github/actions/scan-setup/action.yml
name: Scan Setup
description: "Generic scan setup for SAST or SCA scans"

inputs:
  scan-target:
    description: "The target to scan (e.g., root, frontend, backend)"
    required: true
  artifact-name:
    description: "The desired artifact name for the scan report"
    required: true

outputs:
  report-path:
    description: "Full path to the scan report file"

runs:
  using: "composite"
  steps:
    # Step 1: Ensure the repository is checked out
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Create a reports directory for the target
    - name: Create reports directory
      shell: bash
      run: |
        if [[ "ARTIFACT_NAME" == *"trufflehog"* ]]; then
          mkdir -p sast-reports/${{ inputs.scan-target }}
          REPORT_PATH="sast-reports/$SCAN_TARGET/$ARTIFACT_NAME.json"
        else
          mkdir -p sca-reports/${{ inputs.scan-target }}
          REPORT_PATH="sca-reports/$SCAN_TARGET/$ARTIFACT_NAME.json"
        fi
        
        echo "Report path is $REPORT_PATH"
        echo "report-path=$REPORT_PATH" >> $GITHUB_OUTPUT
