# .github/actions/scan-setup/action.yml
name: Scan Setup
description: "Generic scan setup for SAST or SCA scans"

inputs:
  scan-target:
    description: "The target to scan (e.g., root, frontend, backend)"
    required: true
  artifact-name:
    description: "The desired artifact name for the scan report"
    required: true

outputs:
  report-path:
    description: "Full path to the scan report file"
    value: ${{ steps.compute-report-path.outputs.report-path }}

runs:
  using: "composite"
  steps:
    # Step 1: Ensure the repository is checked out
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Create a reports directory for the target
    - name: Create reports directory
      id: compute-report-path
      shell: bash
      env:
        ARTIFACT_NAME: ${{ inputs.artifact-name }}
        SCAN_TARGET: ${{ inputs.scan-target }}
      run: |
<<<<<<< HEAD
        if [[ "$ARTIFACT_NAME" == *"trufflehog"* ]]; then
          mkdir -p "sast-reports/$SCAN_TARGET"
          REPORT_PATH="sast-reports/$SCAN_TARGET/$ARTIFACT_NAME.json"
        else
          mkdir -p "sca-reports/$SCAN_TARGET"
          REPORT_PATH="sca-reports/$SCAN_TARGET/$ARTIFACT_NAME.json"
        fi
        echo "Report path is $REPORT_PATH"
        echo "report-path=$REPORT_PATH" >> "$GITHUB_OUTPUT"
=======
        if [[ "${{ inputs.artifact-name }}" == *"trufflehog"* ]]; then
          mkdir -p sast-reports/${{ inputs.scan-target }}
          REPORT_PATH="sast-reports/${{ inputs.scan-target }}/${{ inputs.artifact-name }}.json"
        else
          mkdir -p sca-reports/${{ inputs.scan-target }}
          REPORT_PATH="sca-reports/${{ inputs.scan-target }}/${{ inputs.artifact-name }}.json"
        fi
        echo "report-path=$REPORT_PATH" >> $GITHUB_OUTPUT

    # Step 3: Set full report path output
    - name: Set report path output
      shell: bash
      run: |
        REPORT_PATH="reports/${{ inputs.scan-target }}/${{ inputs.artifact-name }}"
        echo "report-path=$REPORT_PATH" >> $GITHUB_OUTPUT
>>>>>>> ddff206 (fix: fix dir error in workflow)
