# .github/actions/scan-setup/action.yml
name: Scan Setup
description: "Generic scan setup for SAST or SCA scans"

inputs:
  scan-target:
    description: "The target to scan (e.g., root, frontend, backend)"
    required: true
  artifact-name:
    description: "The desired artifact name for the scan report"
    required: true

outputs:
  report-path:
    description: "Full path to the scan report file"

runs:
  using: "composite"
  steps:
    # Step 1: Ensure the repository is checked out
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Create a reports directory for the target
    - name: Create reports directory
      shell: bash
      run: |
        mkdir -p reports/${{ inputs.scan-target }}

    # Step 3: Set full report path output
    - name: Set report path output
      shell: bash
      run: |
        REPORT_PATH="reports/${{ inputs.scan-target }}/${{ inputs.artifact-name }}"
        echo "report-path=$REPORT_PATH" >> $GITHUB_OUTPUT
