name: Backend CI, SCA and SAST

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/sca.yml"
      - ".github/workflows/sast.yml"

# Add permissions at the workflow level
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  sca-scan:
    uses: ./.github/workflows/sca.yml
    with:
      scan-target: "backend"
      artifact-name: "backend-retirejs-report"
    secrets: inherit
  
  sast-scan:
    uses: ./.github/workflows/sast.yml
    with:
      scan-target: "backend"
      artifact-name: "backend-trufflehog-report"
    secrets: inherit

  summarize:
    runs-on: ubuntu-latest
    needs: [sca-scan, sast-scan]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Summarize and Post Comment
        uses: ./.github/actions/summarize
        with:
          scan-target: "backend"
          sca-artifact: "backend-retirejs-report"
          sast-artifact: "backend-trufflehog-report"
  
  lint-build:
    name: Lint & Build backend
    runs-on: ubuntu-latest
    needs: summarize

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment with caching enabled for yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Explicitly cache node_modules for potential use in other jobs (optional but can help)
      # Note: setup-node cache is often sufficient, but this provides an explicit layer
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            backend/node_modules # Cache specific workspace deps too if applicable
            backend/node_modules  # Cache specific workspace deps too if applicable
          # Key based on OS and the hash of the yarn lock file
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Run ESLint specifically on the backend workspace
      - name: Run ESLint on backend
        run: yarn workspace backend lint:fix

      # Build the backend application
      - name: Build backend
        run: yarn workspace backend build