name: Backend CI, SCA and SAST

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/sca.yml"
      - ".github/workflows/sast.yml"

# Add permissions at the workflow level
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  sca-scan:
    uses: ./.github/workflows/sca.yml
    with:
      scan-target: "backend"
      artifact-name: "backend-retirejs-report"
    secrets: inherit
  
  sast-scan:
    uses: ./.github/workflows/sast.yml
    with:
      scan-target: "backend"
      artifact-name: "backend-trufflehog-report"
    secrets: inherit

  summarize:
    runs-on: ubuntu-latest
    needs: [sca-scan, sast-scan]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Summarize and Post Comment
        uses: ./.github/actions/summarize
        with:
          scan-target: "backend"
          sca-artifact: "backend-retirejs-report"
          sast-artifact: "backend-trufflehog-report"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  
  lint-build:
    name: Lint & Build backend
    runs-on: ubuntu-latest
    needs: summarize

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment with caching enabled for yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn" # Enable caching based on yarn.lock

      - name: Restore Backend Cache
        uses: actions/cache@v4
        with:
          path: |
            backend/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-backend-${{ hashFiles('backend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-backend-
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run ESLint specifically on the backend workspace
      - name: Run ESLint on backend
        run: yarn backend:lint

      # Build the backend application
      - name: Build backend
        run: yarn backend:build