name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
        
      - name: Install dependencies
        run: |
          pwd
          yarn install --frozen-lockfile  # Install all dependencies at the root level
          yarn --version  # Verify Yarn version
          ls -la node_modules  # Verify node_modules exists

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check installed packages
        run: |
          yarn list --pattern eslint
          ls -la node_modules
      
      - name: Run ESLint
        run: |
          cd frontend
          yarn lint
  
  build:
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Build frontend
        run: |
          cd frontend
          yarn build