name: Frontend CI, SCA and SAST

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/sca.yml"
      - ".github/workflows.sast.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/sca.yml"
      - ".github/workflows.sast.yml"

jobs:
  build_and_lint:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint on Frontend
        run: yarn workspace frontend lint

      - name: Build Frontend
        run: yarn workspace frontend build

  frontend_sca:
    name: Frontend SCA Scan
    needs: build_and_lint
    uses: ./.github/workflows/sca.yml
    with:
      target-dir: frontend
    secrets: inherit
