name: Release Storybook

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - "package.json"
      - "yarn.lock"
      - ".github/workflows/release-storybook.yml"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
<<<<<<< HEAD
  pull-requests: write
=======
>>>>>>> 3abe1fa (FIX: refactor release workflows)

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  release:
    name: Semantic Release (Storybook)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
<<<<<<< HEAD
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            frontend/yarn.lock
=======
>>>>>>> 3abe1fa (FIX: refactor release workflows)

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: yarn install --immutable

      - name: Build Storybook
        working-directory: frontend
        run: yarn build-storybook

      - name: Semantic Release (Storybook, tag-only)
        working-directory: frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e ./frontend/.releaserc.main.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4