# .github/workflows/sast.yml
# Reusable SAST workflow using TruffleHog, dynamically targets frontend/backend/root

name: Reusable SAST (TruffleHog)

on:
  workflow_call:
    inputs:
      scan-target:
        description: 'The target to scan ("root", "backend", or "frontend")'
        required: true
        type: string
      artifact-name:
        description: 'The desired name for the uploaded report artifact (e.g., "frontend-trufflehog-report")'
        required: true
        type: string
    outputs:
      secrets-found:
        description: 'Boolean indicating if secrets were found ("true" or "false")'
        value: ${{ jobs.sast.outputs.secrets-found }}
      report-artifact-name:
        description: "The actual name of the artifact uploaded"
        value: ${{ jobs.sast.outputs.report-artifact-name }}

jobs:
  sast:
    name: TruffleHog Scan (${{ inputs.scan-target }})
    runs-on: ubuntu-latest
    outputs:
      secrets-found: ${{ steps.trufflehog.outputs.secrets-found }}
      report-artifact-name: ${{ inputs.artifact-name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Scan Directory
        id: set_paths
        run: |
          SCAN_TARGET_DIR="." # Default to root
          if [[ "${{ inputs.scan-target }}" == "backend" ]]; then
            SCAN_TARGET_DIR="./backend"
          elif [[ "${{ inputs.scan-target }}" == "frontend" ]]; then
            SCAN_TARGET_DIR="./frontend"
          elif [[ "${{ inputs.scan-target }}" != "root" ]]; then
            echo "Error: Invalid scan target '${{ inputs.scan-target }}'"
            exit 1
          fi
          echo "scan_dir=$SCAN_TARGET_DIR" >> $GITHUB_OUTPUT

      - name: Secret Scanning
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ${{ steps.set_paths.outputs.scan_dir }}
          base: ${{ github.event.repository.default_branch }}
          head: ${{ github.sha }}
          extra_args: --debug --only-verified
        continue-on-error: true

      - name: Check Report Content
        id: check_report
        run: |
          FILE="${{ steps.set_paths.outputs.report_filename }}"
          SECRETS_FOUND="false"

          echo "Checking report content in file: $FILE"
          if [[ -f "$FILE" ]]; then
            if [[ -s "$FILE" ]] && jq -e . "$FILE" >/dev/null 2>&1; then
              COUNT=$(jq '. | length' "$FILE")
              if [[ "$COUNT" -gt 0 ]]; then
                echo "Secrets found: $COUNT"
                SECRETS_FOUND="true"
              else
                echo "No secrets found in the report."
              fi
            else
              echo "Report file is empty or not valid JSON. Assuming no secrets found."
            fi
          else
            echo "Report file $FILE not found. Assuming no secrets found."
            echo "[]" > "$FILE"
          fi
          echo "secrets-found=$SECRETS_FOUND" >> $GITHUB_OUTPUT

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          # Use the input artifact name directly
          name: ${{ inputs.artifact-name }}
          # Use the report_filename from set_paths step
          path: ${{ steps.set_paths.outputs.report_filename }}
          if-no-files-found: error # Fail if the report file is somehow missing
