name: SAST Scan

on:
  workflow_call:
    inputs:
      scan-target:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup report directory
      - name: Prepare SAST report directory
        run: mkdir -p ./sast-reports/${{ inputs.scan-target }}

      # Step 3: Run TruffleHog
      - name: Run TruffleHog Scan
        run: |
          trufflehog filesystem ./ \
            --json \
            > ./sast-reports/${{ inputs.scan-target }}/${{ inputs.scan-target }}-trufflehog-report.json

      # Step 4: Debug (list files to confirm report is created)
      - name: Debug report files
        run: ls -l ./sast-reports/${{ inputs.scan-target }}

      # Step 5: Upload artifact
      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./sast-reports/${{ inputs.scan-target }}/${{ inputs.scan-target }}-trufflehog-report.json
          if-no-files-found: error
