name: SAST Scan

on:
  workflow_call:
    inputs:
      scan-target:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      # Step 0: Checkout repository (required before using local actions)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Setup scan environment
      - name: Setup Scan Environment
        uses: ./.github/actions/scan-setup
        id: setup
        with:
          scan-target: ${{ inputs.scan-target }}
          artifact-name: ${{ inputs.artifact-name }}

      - name: "Debug: Check report directory"
        run: ls -l "$(dirname "${REPORT_PATH}")"
        shell: bash
        env:
          REPORT_PATH: ${{ steps.setup.outputs.report-path }}

      # Step 2: Install TruffleHog (resolve latest Linux binary via GitHub API)
      - name: Install TruffleHog
        shell: bash
        run: |
          set -euo pipefail

          # Ensure jq is available
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y jq
          fi

          ARCHITECTURE="amd64"
          case "$(uname -m)" in
            x86_64|amd64) ARCHITECTURE="amd64" ;;
            aarch64|arm64) ARCHITECTURE="arm64" ;;
            *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
          esac

          echo "Detecting latest TruffleHog release asset for linux/${ARCHITECTURE}..."
          ASSET_URL=$(curl -fsSL https://api.github.com/repos/trufflesecurity/trufflehog/releases/latest \
            | jq -r --arg arch "$ARCHITECTURE" '
                .assets[]
                | select((.name | test("linux"; "i")) and (.name | test($arch; "i")))
                | .browser_download_url
              ' | head -n1)

          if [[ -z "$ASSET_URL" ]]; then
            echo "Could not resolve TruffleHog asset URL for linux/${ARCHITECTURE}." >&2
            exit 1
          fi

          echo "Downloading: $ASSET_URL"
          curl -fsSL "$ASSET_URL" -o trufflehog_asset

          # If the asset is a tar.gz archive, extract the binary; otherwise treat as raw binary
          if file trufflehog_asset | grep -qi 'gzip compressed'; then
            tar -xzf trufflehog_asset trufflehog || tar -xzf trufflehog_asset
            if [[ -f trufflehog ]]; then
              sudo mv trufflehog /usr/local/bin/trufflehog
            else
              # Try to locate the binary within extracted contents
              EXTRACT_DIR=$(mktemp -d)
              tar -xzf trufflehog_asset -C "$EXTRACT_DIR"
              BIN_PATH=$(find "$EXTRACT_DIR" -type f -name 'trufflehog' | head -n1)
              if [[ -z "$BIN_PATH" ]]; then
                echo "Failed to locate trufflehog binary in archive." >&2
                exit 1
              fi
              sudo mv "$BIN_PATH" /usr/local/bin/trufflehog
            fi
          else
            chmod +x trufflehog_asset
            sudo mv trufflehog_asset /usr/local/bin/trufflehog
          fi

          trufflehog --version

      # Step 3: Run TruffleHog Scan (scoped to target dir and excluding noise)
      - name: Run TruffleHog Scan
        shell: bash
        env:
          REPORT_PATH: ${{ steps.setup.outputs.report-path }}
        run: |
          set -e
          TARGET_DIR="."
          case "${{ inputs.scan-target }}" in
            backend) TARGET_DIR="./backend" ;;
            frontend) TARGET_DIR="./frontend" ;;
            root|.) TARGET_DIR="." ;;
          esac

          if [[ "$TARGET_DIR" != "." ]] && [[ ! -d "$TARGET_DIR" ]]; then
            echo "Error: Target directory '$TARGET_DIR' not found after checkout."
            exit 1
          fi

          EXCLUDE_FILE=$(mktemp)
          printf '%s\n' '^\.git/' '(^|/)node_modules/' '(^|/)dist/' '(^|/)coverage/' '(^|/)yarn\.lock$' '(^|/)package-lock\.json$' '(^|/)pnpm-lock\.yaml$' > "$EXCLUDE_FILE"

          echo "Running trufflehog on $TARGET_DIR (excluding common noisy paths)"
          trufflehog filesystem --json --exclude-paths "$EXCLUDE_FILE" "$TARGET_DIR" > "$REPORT_PATH" || true

      # Step 4: Debug (list files)
      - name: Debug report files
        run: ls -l ./sast-reports/${{ inputs.scan-target }}

      # Step 5: Upload artifact
      - name: Upload TruffleHog Report
        if: always() && (github.event_name == 'pull_request' || failure())
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ steps.setup.outputs.report-path }}
          if-no-files-found: error
          retention-days: 7
