name: SAST Scan

on:
  workflow_call:
    inputs:
      scan-target:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup scan environment
      - name: Setup Scan Environment
        uses: ./.github/actions/scan-setup
        id: setup
        with:
          scan-target: ${{ inputs.scan-target }}
          artifact-name: ${{ inputs.artifact-name }}

      - name: "Debug: Check report directory"
        run: ls -l "$(dirname "${REPORT_PATH}")"
        shell: bash
        env:
          REPORT_PATH: ${{ steps.setup.outputs.report-path }}

      # Step 3: Install TruffleHog
      - name: Install TruffleHog
        run: pip install trufflehog

      # Step 4: Run TruffleHog Scan
      - name: Run TruffleHog Scan
        run: trufflehog --json ./ > "$REPORT_PATH"
        shell: bash
        env:
          REPORT_PATH: ${{ steps.setup.outputs.report-path }}


      # Step 5: Debug (list files)
      - name: Debug report files
        run: ls -l ./sast-reports/${{ inputs.scan-target }}

      # Step 5: Upload artifact
      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ steps.setup.outputs.report-path }}
          if-no-files-found: error
